version: "3.1"
services:
  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
    container_name: laravel-basic-php-73-1
    volumes:
      - ./:/var/www/html

  webserver:
    image: nginx:1.17.10
    container_name: laravel-basic-nginx-webserver-1
    links:
      - php:fpm
    environment:
      - FPM_HOST=fpm
      - FPM_PORT=9000
    volumes:
      - ./:/var/www/html
      - ./docker/nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8080:80"
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: laravel-basic-2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: luuduongDB
      MYSQL_USER: duong
      MYSQL_PASSWORD: duong
    ports:
      - 3306:3306
